name: After merge
on:
  push:
    branches:
      - main
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Lint
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Build
        run: make build